import type { Metadata } from "next";
import "./globals.css";
import TanStackProvider from "../components/TanStackProvider/TanStackProvider";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import { Roboto } from "next/font/google";

const robotoFont = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--custom-font",
});

export const metadata: Metadata = {
  title: "08-zustand",
  description: "Generated by home work",
  openGraph: {
    title: "openGraph",
    description: "some description",
    url: "https://www.edu.goit.global/uk/account/login?redirect=%2Fhomepage",
    images: [
      {
        url: "https://picsum.photos/200/300",
        alt: "home image",
        width: 300,
        height: 300,
      },
    ],
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoFont.variable}`}>
        <TanStackProvider>
          <Header />
          {children}
          {modal}
          <Footer />
          <Toaster />
        </TanStackProvider>
      </body>
    </html>
  );
}
